//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avengers.Recursos {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Espanol {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Espanol() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Avengers.Recursos.Espanol", typeof(Espanol).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aceptar.
        /// </summary>
        internal static string btnAceptar {
            get {
                return ResourceManager.GetString("btnAceptar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Añadir.
        /// </summary>
        internal static string btnAdd {
            get {
                return ResourceManager.GetString("btnAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Añadir.
        /// </summary>
        internal static string btnAddLine {
            get {
                return ResourceManager.GetString("btnAddLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Añadir y Nuevo.
        /// </summary>
        internal static string btnAddNew {
            get {
                return ResourceManager.GetString("btnAddNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Añadir.
        /// </summary>
        internal static string btnAddProd {
            get {
                return ResourceManager.GetString("btnAddProd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancelar.
        /// </summary>
        internal static string btnCancel {
            get {
                return ResourceManager.GetString("btnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar.
        /// </summary>
        internal static string btnChange {
            get {
                return ResourceManager.GetString("btnChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Limpiar.
        /// </summary>
        internal static string btnClean {
            get {
                return ResourceManager.GetString("btnClean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cerrar.
        /// </summary>
        internal static string btnCloseTab {
            get {
                return ResourceManager.GetString("btnCloseTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear.
        /// </summary>
        internal static string btnCreate {
            get {
                return ResourceManager.GetString("btnCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Borrar.
        /// </summary>
        internal static string btnDelete {
            get {
                return ResourceManager.GetString("btnDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar.
        /// </summary>
        internal static string btnDeleteUser {
            get {
                return ResourceManager.GetString("btnDeleteUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ejecutar.
        /// </summary>
        internal static string btnEject {
            get {
                return ResourceManager.GetString("btnEject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a                  Salir.
        /// </summary>
        internal static string btnExit {
            get {
                return ResourceManager.GetString("btnExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Facturas.
        /// </summary>
        internal static string btnInvoice {
            get {
                return ResourceManager.GetString("btnInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modificar Factura.
        /// </summary>
        internal static string btnMod {
            get {
                return ResourceManager.GetString("btnMod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modificar.
        /// </summary>
        internal static string btnModify {
            get {
                return ResourceManager.GetString("btnModify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modificar.
        /// </summary>
        internal static string btnModUser {
            get {
                return ResourceManager.GetString("btnModUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nueva Factura.
        /// </summary>
        internal static string btnNew {
            get {
                return ResourceManager.GetString("btnNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nuevo.
        /// </summary>
        internal static string btnNewUser {
            get {
                return ResourceManager.GetString("btnNewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aceptar.
        /// </summary>
        internal static string btnOk {
            get {
                return ResourceManager.GetString("btnOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pedidos.
        /// </summary>
        internal static string btnOrders {
            get {
                return ResourceManager.GetString("btnOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pagar.
        /// </summary>
        internal static string btnPay {
            get {
                return ResourceManager.GetString("btnPay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Imprimir.
        /// </summary>
        internal static string btnPrint {
            get {
                return ResourceManager.GetString("btnPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Quitar.
        /// </summary>
        internal static string btnRemove {
            get {
                return ResourceManager.GetString("btnRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contenido.
        /// </summary>
        internal static string btnShow {
            get {
                return ResourceManager.GetString("btnShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sistema.
        /// </summary>
        internal static string btnSys {
            get {
                return ResourceManager.GetString("btnSys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sacar.
        /// </summary>
        internal static string btnTake {
            get {
                return ResourceManager.GetString("btnTake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Acceder.
        /// </summary>
        internal static string button1 {
            get {
                return ResourceManager.GetString("button1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Salir.
        /// </summary>
        internal static string button2 {
            get {
                return ResourceManager.GetString("button2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Caja.
        /// </summary>
        internal static string cashbook {
            get {
                return ResourceManager.GetString("cashbook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cheque.
        /// </summary>
        internal static string cheq {
            get {
                return ResourceManager.GetString("cheq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Activar.
        /// </summary>
        internal static string ckAct {
            get {
                return ResourceManager.GetString("ckAct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminado.
        /// </summary>
        internal static string ckDel {
            get {
                return ResourceManager.GetString("ckDel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Clientes.
        /// </summary>
        internal static string customers {
            get {
                return ResourceManager.GetString("customers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Deudas.
        /// </summary>
        internal static string debts {
            get {
                return ResourceManager.GetString("debts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Salidas.
        /// </summary>
        internal static string expenses {
            get {
                return ResourceManager.GetString("expenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a En caja.
        /// </summary>
        internal static string inCash {
            get {
                return ResourceManager.GetString("inCash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Entradas.
        /// </summary>
        internal static string incomes {
            get {
                return ResourceManager.GetString("incomes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editorial:.
        /// </summary>
        internal static string label2 {
            get {
                return ResourceManager.GetString("label2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Género:.
        /// </summary>
        internal static string label3 {
            get {
                return ResourceManager.GetString("label3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Precio:.
        /// </summary>
        internal static string label4 {
            get {
                return ResourceManager.GetString("label4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Stock:.
        /// </summary>
        internal static string label6 {
            get {
                return ResourceManager.GetString("label6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Añadir Linea.
        /// </summary>
        internal static string lblAddLine {
            get {
                return ResourceManager.GetString("lblAddLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Añadir Producto.
        /// </summary>
        internal static string lblAddProduct {
            get {
                return ResourceManager.GetString("lblAddProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dirección:.
        /// </summary>
        internal static string lblAdrees {
            get {
                return ResourceManager.GetString("lblAdrees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cantidad:.
        /// </summary>
        internal static string lblAmount {
            get {
                return ResourceManager.GetString("lblAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cantidad:.
        /// </summary>
        internal static string lblAmountAdd {
            get {
                return ResourceManager.GetString("lblAmountAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ciudad:.
        /// </summary>
        internal static string lblCity {
            get {
                return ResourceManager.GetString("lblCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Concepto:.
        /// </summary>
        internal static string lblConcept {
            get {
                return ResourceManager.GetString("lblConcept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Concepto:.
        /// </summary>
        internal static string lblConceptAdd {
            get {
                return ResourceManager.GetString("lblConceptAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cliente:.
        /// </summary>
        internal static string lblCustomer {
            get {
                return ResourceManager.GetString("lblCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cliente:.
        /// </summary>
        internal static string lblCustomerInvoice {
            get {
                return ResourceManager.GetString("lblCustomerInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apellido Cliente.
        /// </summary>
        internal static string lblCustomerSurname {
            get {
                return ResourceManager.GetString("lblCustomerSurname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha:.
        /// </summary>
        internal static string lblDate {
            get {
                return ResourceManager.GetString("lblDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha:.
        /// </summary>
        internal static string lblDateAdd {
            get {
                return ResourceManager.GetString("lblDateAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha Factura:.
        /// </summary>
        internal static string lblDateInvoice {
            get {
                return ResourceManager.GetString("lblDateInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rango de Fechas:.
        /// </summary>
        internal static string lblDateRange {
            get {
                return ResourceManager.GetString("lblDateRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripción:.
        /// </summary>
        internal static string lblDescrip {
            get {
                return ResourceManager.GetString("lblDescrip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descuento:.
        /// </summary>
        internal static string lblDiscount {
            get {
                return ResourceManager.GetString("lblDiscount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a DNI:.
        /// </summary>
        internal static string lblDni {
            get {
                return ResourceManager.GetString("lblDni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Desde:.
        /// </summary>
        internal static string lblFrom {
            get {
                return ResourceManager.GetString("lblFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Código de Entrada:.
        /// </summary>
        internal static string lblIncomes {
            get {
                return ResourceManager.GetString("lblIncomes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ID Factura.
        /// </summary>
        internal static string lblInvoice {
            get {
                return ResourceManager.GetString("lblInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a USUARIO DNI:.
        /// </summary>
        internal static string lblModDni {
            get {
                return ResourceManager.GetString("lblModDni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre:.
        /// </summary>
        internal static string lblName {
            get {
                return ResourceManager.GetString("lblName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nueva contraseña:.
        /// </summary>
        internal static string lblNewPass {
            get {
                return ResourceManager.GetString("lblNewPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a de:.
        /// </summary>
        internal static string lblOf {
            get {
                return ResourceManager.GetString("lblOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña actual:.
        /// </summary>
        internal static string lblOldPass {
            get {
                return ResourceManager.GetString("lblOldPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña.
        /// </summary>
        internal static string lblP {
            get {
                return ResourceManager.GetString("lblP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña:.
        /// </summary>
        internal static string lblPassword {
            get {
                return ResourceManager.GetString("lblPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Forma de Pago:.
        /// </summary>
        internal static string lblPay {
            get {
                return ResourceManager.GetString("lblPay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Permisos.
        /// </summary>
        internal static string lblPermList {
            get {
                return ResourceManager.GetString("lblPermList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Teléfono:.
        /// </summary>
        internal static string lblPhone {
            get {
                return ResourceManager.GetString("lblPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pagado.
        /// </summary>
        internal static string lblPrepago {
            get {
                return ResourceManager.GetString("lblPrepago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Precio:.
        /// </summary>
        internal static string lblPrice {
            get {
                return ResourceManager.GetString("lblPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Precio:.
        /// </summary>
        internal static string lblPricesale {
            get {
                return ResourceManager.GetString("lblPricesale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Producto:.
        /// </summary>
        internal static string lblProduct {
            get {
                return ResourceManager.GetString("lblProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Provincia:.
        /// </summary>
        internal static string lblProvince {
            get {
                return ResourceManager.GetString("lblProvince", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Región:.
        /// </summary>
        internal static string lblRegion {
            get {
                return ResourceManager.GetString("lblRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Repite nueva contraseña:.
        /// </summary>
        internal static string lblRepPass {
            get {
                return ResourceManager.GetString("lblRepPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rol:.
        /// </summary>
        internal static string lblRol {
            get {
                return ResourceManager.GetString("lblRol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre rol:.
        /// </summary>
        internal static string lblRoleName {
            get {
                return ResourceManager.GetString("lblRoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Permisos seleccionados.
        /// </summary>
        internal static string lblSelectedPerm {
            get {
                return ResourceManager.GetString("lblSelectedPerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Selecciona Idioma.
        /// </summary>
        internal static string lblSelectIdioma {
            get {
                return ResourceManager.GetString("lblSelectIdioma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Origen:.
        /// </summary>
        internal static string lblSource {
            get {
                return ResourceManager.GetString("lblSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Origen:.
        /// </summary>
        internal static string lblSourceAdd {
            get {
                return ResourceManager.GetString("lblSourceAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apellido:.
        /// </summary>
        internal static string lblSurname {
            get {
                return ResourceManager.GetString("lblSurname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Objetivo:.
        /// </summary>
        internal static string lblTarget {
            get {
                return ResourceManager.GetString("lblTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hasta:.
        /// </summary>
        internal static string lblTo {
            get {
                return ResourceManager.GetString("lblTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo de Pago:.
        /// </summary>
        internal static string lblTPayment {
            get {
                return ResourceManager.GetString("lblTPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo:.
        /// </summary>
        internal static string lblType {
            get {
                return ResourceManager.GetString("lblType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo:.
        /// </summary>
        internal static string lblTypes {
            get {
                return ResourceManager.GetString("lblTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo:.
        /// </summary>
        internal static string lblTypesAdd {
            get {
                return ResourceManager.GetString("lblTypesAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario.
        /// </summary>
        internal static string lblU {
            get {
                return ResourceManager.GetString("lblU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario:.
        /// </summary>
        internal static string lblUser {
            get {
                return ResourceManager.GetString("lblUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario:.
        /// </summary>
        internal static string lblUserAdd {
            get {
                return ResourceManager.GetString("lblUserAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pendiente pago.
        /// </summary>
        internal static string pendingPayment {
            get {
                return ResourceManager.GetString("pendingPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Productos.
        /// </summary>
        internal static string products {
            get {
                return ResourceManager.GetString("products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Completo.
        /// </summary>
        internal static string rbComplete {
            get {
                return ResourceManager.GetString("rbComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Parcial.
        /// </summary>
        internal static string rbPartial {
            get {
                return ResourceManager.GetString("rbPartial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ascendente.
        /// </summary>
        internal static string rbtnAscend {
            get {
                return ResourceManager.GetString("rbtnAscend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descendente.
        /// </summary>
        internal static string rbtnDescend {
            get {
                return ResourceManager.GetString("rbtnDescend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Recibo.
        /// </summary>
        internal static string receips {
            get {
                return ResourceManager.GetString("receips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuarios.
        /// </summary>
        internal static string users {
            get {
                return ResourceManager.GetString("users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Validar.
        /// </summary>
        internal static string Validation {
            get {
                return ResourceManager.GetString("Validation", resourceCulture);
            }
        }
    }
}
