//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avengers.Recursos {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Ingles {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Ingles() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Avengers.Recursos.Ingles", typeof(Ingles).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Accept.
        /// </summary>
        internal static string btnAceptar {
            get {
                return ResourceManager.GetString("btnAceptar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add.
        /// </summary>
        internal static string btnAdd {
            get {
                return ResourceManager.GetString("btnAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add and New.
        /// </summary>
        internal static string btnAddNew {
            get {
                return ResourceManager.GetString("btnAddNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancel.
        /// </summary>
        internal static string btnCancel {
            get {
                return ResourceManager.GetString("btnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Save.
        /// </summary>
        internal static string btnChange {
            get {
                return ResourceManager.GetString("btnChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Clean.
        /// </summary>
        internal static string btnClean {
            get {
                return ResourceManager.GetString("btnClean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Close.
        /// </summary>
        internal static string btnCloseTab {
            get {
                return ResourceManager.GetString("btnCloseTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Create.
        /// </summary>
        internal static string btnCreate {
            get {
                return ResourceManager.GetString("btnCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Delete.
        /// </summary>
        internal static string btnDelete {
            get {
                return ResourceManager.GetString("btnDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Delete.
        /// </summary>
        internal static string btnDeleteUser {
            get {
                return ResourceManager.GetString("btnDeleteUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Execute.
        /// </summary>
        internal static string btnEject {
            get {
                return ResourceManager.GetString("btnEject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a                  Exit.
        /// </summary>
        internal static string btnExit {
            get {
                return ResourceManager.GetString("btnExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modify.
        /// </summary>
        internal static string btnModify {
            get {
                return ResourceManager.GetString("btnModify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modify.
        /// </summary>
        internal static string btnModUser {
            get {
                return ResourceManager.GetString("btnModUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a New.
        /// </summary>
        internal static string btnNewUser {
            get {
                return ResourceManager.GetString("btnNewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ok.
        /// </summary>
        internal static string btnOk {
            get {
                return ResourceManager.GetString("btnOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Orders.
        /// </summary>
        internal static string btnOrders {
            get {
                return ResourceManager.GetString("btnOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pay.
        /// </summary>
        internal static string btnPay {
            get {
                return ResourceManager.GetString("btnPay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Remove.
        /// </summary>
        internal static string btnRemove {
            get {
                return ResourceManager.GetString("btnRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a System.
        /// </summary>
        internal static string btnSys {
            get {
                return ResourceManager.GetString("btnSys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Take Out.
        /// </summary>
        internal static string btnTake {
            get {
                return ResourceManager.GetString("btnTake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Login.
        /// </summary>
        internal static string button1 {
            get {
                return ResourceManager.GetString("button1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Exit.
        /// </summary>
        internal static string button2 {
            get {
                return ResourceManager.GetString("button2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cashbook.
        /// </summary>
        internal static string cashbook {
            get {
                return ResourceManager.GetString("cashbook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Check.
        /// </summary>
        internal static string cheq {
            get {
                return ResourceManager.GetString("cheq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Activate.
        /// </summary>
        internal static string ckAct {
            get {
                return ResourceManager.GetString("ckAct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Deleted.
        /// </summary>
        internal static string ckDel {
            get {
                return ResourceManager.GetString("ckDel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Customers.
        /// </summary>
        internal static string customers {
            get {
                return ResourceManager.GetString("customers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debts.
        /// </summary>
        internal static string debts {
            get {
                return ResourceManager.GetString("debts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Expenses.
        /// </summary>
        internal static string expenses {
            get {
                return ResourceManager.GetString("expenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a In-Cash.
        /// </summary>
        internal static string inCash {
            get {
                return ResourceManager.GetString("inCash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Incomes.
        /// </summary>
        internal static string incomes {
            get {
                return ResourceManager.GetString("incomes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editorial:.
        /// </summary>
        internal static string label2 {
            get {
                return ResourceManager.GetString("label2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gender:.
        /// </summary>
        internal static string label3 {
            get {
                return ResourceManager.GetString("label3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Price:.
        /// </summary>
        internal static string label4 {
            get {
                return ResourceManager.GetString("label4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Stock:.
        /// </summary>
        internal static string label6 {
            get {
                return ResourceManager.GetString("label6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Address:.
        /// </summary>
        internal static string lblAdrees {
            get {
                return ResourceManager.GetString("lblAdrees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Amount:.
        /// </summary>
        internal static string lblAmount {
            get {
                return ResourceManager.GetString("lblAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Amount:.
        /// </summary>
        internal static string lblAmountAdd {
            get {
                return ResourceManager.GetString("lblAmountAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a City:.
        /// </summary>
        internal static string lblCity {
            get {
                return ResourceManager.GetString("lblCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Concept:.
        /// </summary>
        internal static string lblConcept {
            get {
                return ResourceManager.GetString("lblConcept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Concept:.
        /// </summary>
        internal static string lblConceptAdd {
            get {
                return ResourceManager.GetString("lblConceptAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Customer:.
        /// </summary>
        internal static string lblCustomer {
            get {
                return ResourceManager.GetString("lblCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Date:.
        /// </summary>
        internal static string lblDate {
            get {
                return ResourceManager.GetString("lblDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Date:.
        /// </summary>
        internal static string lblDateAdd {
            get {
                return ResourceManager.GetString("lblDateAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Date Range:.
        /// </summary>
        internal static string lblDateRange {
            get {
                return ResourceManager.GetString("lblDateRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Description:.
        /// </summary>
        internal static string lblDescrip {
            get {
                return ResourceManager.GetString("lblDescrip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Discount:.
        /// </summary>
        internal static string lblDiscount {
            get {
                return ResourceManager.GetString("lblDiscount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a DNI:.
        /// </summary>
        internal static string lblDni {
            get {
                return ResourceManager.GetString("lblDni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a From:.
        /// </summary>
        internal static string lblFrom {
            get {
                return ResourceManager.GetString("lblFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Incomes Source:.
        /// </summary>
        internal static string lblIncomes {
            get {
                return ResourceManager.GetString("lblIncomes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a USER DNI:.
        /// </summary>
        internal static string lblModDni {
            get {
                return ResourceManager.GetString("lblModDni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Name:.
        /// </summary>
        internal static string lblName {
            get {
                return ResourceManager.GetString("lblName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a New password:.
        /// </summary>
        internal static string lblNewPass {
            get {
                return ResourceManager.GetString("lblNewPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Of:.
        /// </summary>
        internal static string lblOf {
            get {
                return ResourceManager.GetString("lblOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Current password:.
        /// </summary>
        internal static string lblOldPass {
            get {
                return ResourceManager.GetString("lblOldPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password.
        /// </summary>
        internal static string lblP {
            get {
                return ResourceManager.GetString("lblP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password:.
        /// </summary>
        internal static string lblPassword {
            get {
                return ResourceManager.GetString("lblPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PaymentMethod:.
        /// </summary>
        internal static string lblPay {
            get {
                return ResourceManager.GetString("lblPay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Permissions.
        /// </summary>
        internal static string lblPermList {
            get {
                return ResourceManager.GetString("lblPermList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Phone:.
        /// </summary>
        internal static string lblPhone {
            get {
                return ResourceManager.GetString("lblPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Prepaid:.
        /// </summary>
        internal static string lblPrepago {
            get {
                return ResourceManager.GetString("lblPrepago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pricesale:.
        /// </summary>
        internal static string lblPricesale {
            get {
                return ResourceManager.GetString("lblPricesale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Product:.
        /// </summary>
        internal static string lblProduct {
            get {
                return ResourceManager.GetString("lblProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Province:.
        /// </summary>
        internal static string lblProvince {
            get {
                return ResourceManager.GetString("lblProvince", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Region:.
        /// </summary>
        internal static string lblRegion {
            get {
                return ResourceManager.GetString("lblRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Repeat new password:.
        /// </summary>
        internal static string lblRepPass {
            get {
                return ResourceManager.GetString("lblRepPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Role:.
        /// </summary>
        internal static string lblRol {
            get {
                return ResourceManager.GetString("lblRol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Role Name:.
        /// </summary>
        internal static string lblRoleName {
            get {
                return ResourceManager.GetString("lblRoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Selected permissions.
        /// </summary>
        internal static string lblSelectedPerm {
            get {
                return ResourceManager.GetString("lblSelectedPerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select Languaje.
        /// </summary>
        internal static string lblSelectIdioma {
            get {
                return ResourceManager.GetString("lblSelectIdioma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Source:.
        /// </summary>
        internal static string lblSource {
            get {
                return ResourceManager.GetString("lblSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Source:.
        /// </summary>
        internal static string lblSourceAdd {
            get {
                return ResourceManager.GetString("lblSourceAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Surname:.
        /// </summary>
        internal static string lblSurname {
            get {
                return ResourceManager.GetString("lblSurname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Target:.
        /// </summary>
        internal static string lblTarget {
            get {
                return ResourceManager.GetString("lblTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a To:.
        /// </summary>
        internal static string lblTo {
            get {
                return ResourceManager.GetString("lblTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Payment Type:.
        /// </summary>
        internal static string lblTPayment {
            get {
                return ResourceManager.GetString("lblTPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Type:.
        /// </summary>
        internal static string lblType {
            get {
                return ResourceManager.GetString("lblType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Types:.
        /// </summary>
        internal static string lblTypes {
            get {
                return ResourceManager.GetString("lblTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Types:.
        /// </summary>
        internal static string lblTypesAdd {
            get {
                return ResourceManager.GetString("lblTypesAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a User.
        /// </summary>
        internal static string lblU {
            get {
                return ResourceManager.GetString("lblU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a User:.
        /// </summary>
        internal static string lblUser {
            get {
                return ResourceManager.GetString("lblUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a User:.
        /// </summary>
        internal static string lblUserAdd {
            get {
                return ResourceManager.GetString("lblUserAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pending Payment.
        /// </summary>
        internal static string pendingPayment {
            get {
                return ResourceManager.GetString("pendingPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Products.
        /// </summary>
        internal static string products {
            get {
                return ResourceManager.GetString("products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Complete.
        /// </summary>
        internal static string rbComplete {
            get {
                return ResourceManager.GetString("rbComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Partial.
        /// </summary>
        internal static string rbPartial {
            get {
                return ResourceManager.GetString("rbPartial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ascend.
        /// </summary>
        internal static string rbtnAscend {
            get {
                return ResourceManager.GetString("rbtnAscend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descend.
        /// </summary>
        internal static string rbtnDescend {
            get {
                return ResourceManager.GetString("rbtnDescend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Receips.
        /// </summary>
        internal static string receips {
            get {
                return ResourceManager.GetString("receips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Users.
        /// </summary>
        internal static string users {
            get {
                return ResourceManager.GetString("users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Validation.
        /// </summary>
        internal static string Validation {
            get {
                return ResourceManager.GetString("Validation", resourceCulture);
            }
        }
    }
}
